# Generated by Django 4.0.3 on 2022-03-22 12:35
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_rename_nome_curso_codig_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='codig_curso',
            new_name='codigo_curso',
        ),
    ]
